server:
  port: 8087
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tplogistics?characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  
